### ISSUE TITLE
require(APP_ROOT + '/foo')

### ISSUE THREAD

**Issue by leeoniya** [eight04/cjs-es#25]
hey @eight04 ,

I guess there's no built-in way to require from a path relative to some pre-defined global app root in Node. There sure are a lot of userland npm modules for this. It might be nice to add support for something basic. My current thought is to just configure a pre-defined global [1]. This would allow cjs modules to work normally in node but also properly convert to es imports/exports.

Maybe there's nothing cjs-es can do here, i dunno.

For now, I can probably work around this by setting a global in Node and using a rollup/regex-replace plugin to swap APP_ROOT before passing it on to cjs-es.

[1] https://gist.github.com/branneman/8048520#3-the-global

**Comment by eight04** [comment]
Technically, `import foo from APP_ROOT + './foo';` is not a valid statement. `import` only accepts a single/double-quoted string as the module ID.

So yes, I think you have to replace the expression with plain string before running cjs-es.

You can create a plugin which automatically tracks global assignments e.g. `global.APP_ROOT = '...'` and evaluates binary expressions containing the variable. But I think it will be easier to use the re plugin.

**Comment by leeoniya** [comment]
ok, sounds good.
