### ISSUE TITLE
Document nested option

### ISSUE THREAD

**Issue by creamidea** [eight04/cjs-es#26]
code: a.js
```js
require('./c');

if (true) {
  require('./a');
} else {
  require('./b');
}

function A () {
  console.log('hhhh');
}

module.exports = A;
```

and I use the below code to transform
```js
const fs = require('fs');
const {parse} = require("acorn");
const {transform} = require("cjs-es");
const code = fs.readFileSync('./a.js', 'utf-8');
transform({code, parse})
  .then(result => {
    console.log(result.code);
  });
```

the result show that not working in if-else block
![image](https://user-images.githubusercontent.com/1274730/99785450-2272d700-2b58-11eb-87c3-e239060f1de4.png)

acorn: 8.0.4
cjs-es: 0.8.2

**Comment by eight04** [comment]
Hmm I forgot to document the `nested` option in README. Try
```js
transform({code, parse, nested: true})
```

**Comment by creamidea** [comment]
Yeah, it works. 😄 

and support the function below?

![image](https://user-images.githubusercontent.com/1274730/99786819-eb9dc080-2b59-11eb-8b50-76eb906511b8.png)

**Comment by creamidea** [comment]
> Yeah, it works. 😄
> 
> and support the function below?
> 
> ![image](https://user-images.githubusercontent.com/1274730/99786819-eb9dc080-2b59-11eb-8b50-76eb906511b8.png)

Or is this the duty of the terser ?

**Comment by eight04** [comment]
You have to use other minifier/bundler to remove dead code like terser/rollup.

BTW, even if the entire if/else block will be removed, the tool probably won't remove the import statement since importing may cause extra side effects.

**Comment by creamidea** [comment]
OK, thanks

**Comment by eight04** [comment]
Let's keep this open until I fix the readme.

**Comment by creamidea** [comment]
> You have to use other minifier/bundler to remove dead code like terser/rollup.
> 
> BTW, even if the entire if/else block will be removed, the tool probably won't remove the import statement since importing may cause extra side effects.

If I want to remove the import statement, what can I do?

**Comment by eight04** [comment]
For this simple case, I think you can run terser first before running cjs-es so `require('./b');` will be removed completely.

In a large project that uses bundler, it will be easier to shim unneeded modules with an empty one.

**Comment by eight04** [comment]
Done
